AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  endpoints

  Sample SAM Template for endpoints
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  UploadVideoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload-video/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
          - S3WritePolicy:        # Policy template with placeholder value
              BucketName: radar-speed-sign
      Events:
        UploadVideo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload-video
            Method: post
            Auth:
              ApiKeyRequired: true
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RadarSpeedTestApi:
    Description: "API Gateway endpoint URL for Prod stage for radar-speed-test functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload-video/"
  UploadVidoFunction:
    Description: "UploadVideo Lambda Function ARN"
    Value: !GetAtt UploadVideoFunction.Arn
  UploadVideoFunctionIamRole:
    Description: "Implicit IAM Role created for Upload Video function"
    Value: !GetAtt UploadVideoFunctionRole.Arn
